server:
  port: 8082

spring:
  # spring batch   initial databaseï¼Œfile in jar
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: always
      mode: never
#batch create file path
job:
  data:
    path: D:/demo
